### ISSUE TITLE
dplyr dependency

### ISSUE THREAD

**Issue by davidaarmstrong** [svmiller/stevemisc#1]
Hi Steve, 

Just using your `btscs` function.  One small bug is that you need to import the `dplyr` package in the namespace, otherwise the `eqno` function is undefined.  Importing `tidyverse` apparently doesn't import everything in the tidyverse.  

Best, 
Dave.

**Comment by svmiller** [comment]
Thanks for letting me know about that. I think because I knee-jerk load my package after `library(tidyverse)`, I never noticed this was an issue. I think I took care of it, though I'll confess I need to get better at writing R packages.

**Comment by davidaarmstrong** [comment]
Hi Steve,

Thanks.  It seems for me like writing R packages is always one of those
things that never gets much easier.  There are always tons of things I
forget and the CRAN check is always throwing new errors, so I probably need
to get better at writing R packages, too.

Best,
Dave.


On June 19, 2018 at 1:34:48 PM, Steven V. Miller (notifications@github.com)
wrote:

Thanks for letting me know about that. I think because I knee-jerk load my
package after library(tidyverse), I never noticed this was an issue. I
think I took care of it, though I'll confess I need to get better at
writing R packages.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/svmiller/stevemisc/issues/1#issuecomment-398482371>,
or mute
the thread
